name: CI

on: [push, pull_request]

jobs:
  build_latest:
    name: Node latest
    runs-on: ubuntu-latest
    container: node:latest
    steps:
      - uses: actions/checkout@v1
      - name: install system dependencies
        run: apt-get update && apt-get -y install xvfb libgtk-3-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2
      - name: install dependencies
        run: yarn
      - name: build sources
        run: yarn build
      - name: run tests
        run: yarn test

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    container: node:latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v1
      - name: Deploy on Zeit
        uses: actions/zeit-now@master
